[package]
name = "advent-of-code-2015"
version = "0.1.0"
authors = ["sree <rajan.sreeraj@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
regex = "1"
rayon = "1.5"
lazy_static = "1.4.0"